name: Release Package

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release-zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: ZIP Component Dir
        run: |
          cd ${{ github.workspace }}/custom_components/fan_controller
          zip -r home_assistant_fan_controller.zip ./

      - name: Upload zip to release
        uses: svenstaro/upload-release-action@29e53e917877a24fad85510ded594ab3c9ca12de # v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/custom_components/fan_controller/home_assistant_fan_controller.zip
          asset_name: home_assistant_fan_controller.zip
          tag: ${{ github.ref }}
          overwrite: true
